spring:
    zipkin:
        base-url: http://localhost:9411
eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: //localhost:8761/eureka/
    instance:
        hostname: employee-service
