spring:
    zipkin:
        base-url: http://localhost:9411
    kafka:
    bootstrap-servers: localhost:9092

        
eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka/
    instance:
        hostname: service-employee
    
